####################################################
# DVrouter.py
# Name: Nguyen Nhat Phu
# HUID: 24022708
#####################################################

from router import Router
import json
from packet import Packet

INFINITY = 16  # Ngưỡng vô cực, xử lý count-to-infinity

class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.dv = {self.addr: 0}          # Distance vector của router này: {dst: cost}
        self.neighbor_dvs = {}             # DV nhận từ hàng xóm: {neighbor: {dst: cost}}
        self.forwarding_table = {}         # Bảng chuyển tiếp: {dst: port}
        self.links_info = {}               # Thông tin link: {port: (neighbor_addr, cost)}
    
    # --- Helper: tính lại DV và forwarding table theo Bellman-Ford ---
    def _recompute(self):
        """Tính lại DV, trả về True nếu có thay đổi."""
        new_dv = {self.addr: 0}
        new_fwd = {}
        all_dests = set()
        for ndv in self.neighbor_dvs.values():
            all_dests.update(ndv.keys())
        for dst in all_dests:
            if dst == self.addr:
                continue
            best_cost = INFINITY
            best_port = None
            for port, (neighbor, link_cost) in self.links_info.items():
                ndv = self.neighbor_dvs.get(neighbor, {})
                cost_via = link_cost + ndv.get(dst, INFINITY)
                if cost_via < best_cost:
                    best_cost = cost_via
                    best_port = port
            if best_cost < INFINITY:
                new_dv[dst] = best_cost
                new_fwd[dst] = best_port
        changed = (new_dv != self.dv)
        self.dv = new_dv
        self.forwarding_table = new_fwd
        return changed

    # --- Helper: broadcast DV của mình tới tất cả hàng xóm ---
    def _broadcast_dv(self):
        for port, (neighbor, _) in self.links_info.items():
            packet = Packet(Packet.ROUTING, self.addr, neighbor,
                            content=json.dumps(self.dv))
            self.send(port, packet)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table:
                self.send(self.forwarding_table[packet.dst_addr], packet)
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors
            neighbor = packet.src_addr
            received_dv = json.loads(packet.content)
            if self.neighbor_dvs.get(neighbor) != received_dv:
                self.neighbor_dvs[neighbor] = received_dv
                changed = self._recompute()
                if changed:
                    self._broadcast_dv()

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        # self.dv[endpoint] = cost
        # self.forwarding_table[endpoint] = port
        self.links_info[port] = (endpoint, cost)
        self.neighbor_dvs[endpoint] = {endpoint: 0}
        self._recompute()
        self._broadcast_dv()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        if port in self.links_info:
            neighbor, _ = self.links_info.pop(port)
            self.neighbor_dvs.pop(neighbor, None)
        self._recompute()
        self._broadcast_dv()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            self._broadcast_dv()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr})"
