####################################################
# LSrouter.py
# Name: Nguyen Nhat Phu
# HUID: 24022708
#####################################################

from router import Router
import json
from router import Router
from packet import Packet


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.seq = 0                  # Sequence number của router này
        self.link_states = {self.addr: {}}   # LS toàn mạng: {router: {neighbor: cost}}
        self.seq_nums = {self.addr: 0}       # Sequence number mới nhất của từng router
        self.links_info = {}                 # Link trực tiếp: {port: (neighbor, cost)}
        self.forwarding_table = {}           # Bảng chuyển tiếp: {dst: port}
        
    # --- Helper: tính lại forwarding table bằng Dijkstra ---
    def _recompute(self):
        # Khởi tạo khoảng cách
        dist = {self.addr: 0}
        prev_router = {}   # {dst: router_truoc_do}
        prev_port = {}     # {dst: port_de_di}
        unvisited = set(self.link_states.keys())
        unvisited.add(self.addr)

        while unvisited:
            # Chọn node chưa thăm có dist nhỏ nhất
            u = None
            for node in unvisited:
                if node in dist:
                    if u is None or dist[node] < dist[u]:
                        u = node
            if u is None:
                break
            unvisited.remove(u)

            # Duyệt các neighbor của u
            neighbors = self.link_states.get(u, {})
            for v, cost in neighbors.items():
                new_cost = dist[u] + cost
                if v not in dist or new_cost < dist[v]:
                    dist[v] = new_cost
                    prev_router[v] = u

        # Xây dựng forwarding table: tìm port để đi tới từng dst
        self.forwarding_table = {}
        for dst in dist:
            if dst == self.addr:
                continue
            # Trace back đường đi từ dst về self.addr
            node = dst
            while prev_router.get(node) != self.addr:
                node = prev_router.get(node)
                if node is None:
                    break
            if node is None:
                continue
            # node là neighbor trực tiếp của self.addr trên đường tới dst
            for port, (neighbor, _) in self.links_info.items():
                if neighbor == node:
                    self.forwarding_table[dst] = port
                    break
        
    # --- Helper: broadcast LS của mình tới tất cả hàng xóm ---
    def _broadcast_ls(self, from_port=None):
        """Gửi LS của router này ra tất cả port, trừ from_port."""
        content = json.dumps({
            "src": self.addr,
            "seq": self.seq,
            "ls": self.link_states[self.addr]
        })
        for port, (neighbor, _) in self.links_info.items():
            if port != from_port:
                packet = Packet(Packet.ROUTING, self.addr, neighbor, content=content)
                self.send(port, packet)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table:
                self.send(self.forwarding_table[packet.dst_addr], packet)
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors
            data = json.loads(packet.content)
            src = data["src"]
            seq = data["seq"]
            ls = data["ls"]
            
            # Chỉ xử lý nếu sequence number mới hơn
            if seq <= self.seq_nums.get(src, -1):
                return

            self.seq_nums[src] = seq
            self.link_states[src] = ls
            self._recompute()
            # Flood tiếp sang hàng xóm khác (trừ port nhận vào)
            content = json.dumps({"src": src, "seq": seq, "ls": ls})
            for p, (neighbor, _) in self.links_info.items():
                if p != port:
                    pkt = Packet(Packet.ROUTING, self.addr, neighbor, content=content)
                    self.send(p, pkt)


    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        self.links_info[port] = (endpoint, cost)
        self.link_states[self.addr][endpoint] = cost
        self.seq += 1
        self.seq_nums[self.addr] = self.seq
        self._recompute()
        self._broadcast_ls()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        if port in self.links_info:
            neighbor, _ = self.links_info.pop(port)
            self.link_states[self.addr].pop(neighbor, None)
            self.seq += 1
            self.seq_nums[self.addr] = self.seq
        self._recompute()
        self._broadcast_ls()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the link state of this router to all neighbors
            self._broadcast_ls()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
